field.value.id_field:
  type: mapping
  label: ID field
  mapping:
    value:
      type: label
      label: Value

field.storage_settings.id_field:
  type: field.storage_settings.string
  label: 'ID field settings'

field.formatter.settings.id_field:
  type: field.formatter.settings.string
